<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Messages [
  <!ELEMENT Messages (Package*)>

  <!ELEMENT Package (Error*)>
  <!ATTLIST Package ID CDATA #REQUIRED>
  <!ATTLIST Package DefaultComponent CDATA #REQUIRED>

  <!ELEMENT Error (#PCDATA)>
  <!ATTLIST Error Key ID #REQUIRED>
  <!ATTLIST Error Component CDATA #IMPLIED>
  <!ATTLIST Error NativeErrorCode CDATA #REQUIRED>
  <!ATTLIST Error Params CDATA "0">
]>

<Messages>
    <!-- Package DS_ERROR. ID corresponds to the DS_ERROR constant defined in DriverSupport.h -->
    <Package ID="110" DefaultComponent="DriverSupport">
        <!-- Error thrown when an error occurs while trying to load a string resource for the dialog. -->
        <Error Key="DSStringResourceError" Params="1" NativeErrorCode="1000">String resource %1% not found.</Error>

        <!-- Error thrown when an error occurs while trying to load a cursor resource.. -->
        <Error Key="DSCursorResourceError" Params="1" NativeErrorCode="1010">An error occurred while attempting to load a cursor: %1%</Error>

        <!-- Error thrown when an error occurs while trying to encrypt data. -->
        <Error Key="DSEncryptError" Params="1" NativeErrorCode="1020">An error occurred while attempting to encrypt data: %1%</Error>
      
        <!-- Error thrown when an error occurs while trying to decrypt data. -->
        <Error Key="DSDecryptError" Params="1" NativeErrorCode="1030">Failed to decrypt data: %1%</Error>
      
        <!-- Error thrown when an error occurs while trying to initialize SSL context. -->
         <Error Key="DSSSLError" Params="1" NativeErrorCode="1040">Failed to initialize SSL context: %1%</Error>
     
        <!-- Error thrown when OpenSSL was unable to allocate enough memory. -->
        <Error Key="DSOpenSSLOutofMemory" Params="1" NativeErrorCode="1041">An error occurred while allocating memory to create: %1%</Error>

        <!-- Error thrown when an error occurs while converting server SSL certificate into CryptoAPI format. -->
        <Error Key="DSSSLServerCertConvertError" Params="0" NativeErrorCode="1050">Failed to convert certificate from OpenSSL to CryptoAPI.</Error>

        <!-- Error thrown when an the driver has been locked by a vendor. -->
        <Error Key="DSDriverLockedError" Params="1" NativeErrorCode="1060">Driver has been locked by the vendor %1% and is not licensed for use with this application.</Error>

        <!-- Error thrown when an the driver has been locked by a vendor. -->
        <Error Key="DSDIDFileMissingError" Params="1" NativeErrorCode="1070">Cannot access file %1%. The driver cannot function properly without the file.</Error>

        <!-- Error thrown when OpenSSL functions return an error. -->
        <Error Key="DSOpenSSLError" Params="2" NativeErrorCode="1080">OpenSSL function %1% returned error: %2%</Error>

        <!-- Error thrown when CSV parser encounters an error. -->
        <Error Key="CSVParser" Params="1" NativeErrorCode="1090">Error parsing CSV. [%1%]</Error>

        <!-- Error thrown when SSL verification fails because trust store does not have right CA certs to verify the server certificate. -->
        <Error Key="DSSslNoCaError" Params="0" NativeErrorCode="1100">SSL certificate verification failed because the certificate is missing or incorrect.</Error>

        <!-- Error thrown when cURL is not able to receive the expected response from the server due to either incorrect host/port specified or SSL not enabled for connection when connecting to SSL enabled server. -->
        <Error Key="DSCurlRecvError" Params="0" NativeErrorCode="1110">Unexpected response received from server. Please ensure the server host and port specified for the connection are correct and confirm if SSL should be enabled for the connection.</Error>

        <!-- Error thrown when server host name does not match server SSL certificate subject common name (CN) or any of the "DNS Name" entries in the "Subject Alternative Name". -->
        <Error Key="DSServerHostAndCnSubjectMismatch" Params="0" NativeErrorCode="1120">SSL verification failed because the server host name specified for the connection does not match the "CN" entry in the "Subject" field or any of the "DNS Name" entries of the "Subject Alternative Name" field in the server certificate.</Error>

        <!-- Error thrown when enabling SSL for the connection when connecting to a server that has not enabled SSL.-->
        <Error Key="DSSslConnectionToNonSslServerError" Params="0" NativeErrorCode="1130">Cannot enable SSL for the connection when connecting to a server that has not enabled SSL.</Error>

        <!-- Error thrown when CA certificates can not be read from the CA certificates file. -->
        <Error Key="DSCaCertsFileLoadError" Params="0" NativeErrorCode="1140">Unable to load CA certificates from certs file location.  Please ensure the file exists, has read permission, and has the correct PEM format.</Error>

        <!-- Error thrown when enabling SSL for the connection when connecting to a server that has not enabled SSL or if server has been configured to use SSLv2 or SSLv3 but they are not allowed by the driver.-->
        <Error Key="DSSslConnectErrorSsl2AndSsl3NotAllowed" Params="0" NativeErrorCode="1150">Cannot enable SSL for the connection when connecting to a server that has not enabled SSL. If the server has SSL enabled, please check if it has been configured to use SSLv2 or SSLv3 protocols. SSLv2 and SSLv3 protocols are not allowed by the driver as they are insecure.</Error>

        <!-- Error thrown when enabling SSL for the connection when connecting to a server that has not enabled SSL or if server has been configured to use SSL protocol version lower than what is allowed by the connection.-->
        <Error Key="DSSslConnectErrorLowerThanMinTls" Params="1" NativeErrorCode="1160">Cannot enable SSL for the connection when connecting to a server that has not enabled SSL. If the server has SSL enabled, please check if it has been configured to use a SSL protocol version that is lower than what is allowed for the connection. The minimum SSL protocol version allowed for the connection is: %1%.</Error>

        <!-- Error thrown when driver is not able to receive the expected response from the server due to incorrect host/port specified. -->
        <Error Key="DSWrongServerError" Params="0" NativeErrorCode="1170">Unexpected response received from server. Please ensure the server host and port specified for the connection are correct.</Error>

        <!-- Error thrown when driver is not able to receive an invalid port valid. -->
        <Error Key="DSInvalidPortError" Params="1" NativeErrorCode="1180">Incorrect %1% specified. Please check your configuration.</Error>

        <!-- Error thrown when the client private key properties are not provided while two-way SSL feature is enabled. -->
        <Error Key="DSClientPrivateKeyPropsNeededError" Params="0" NativeErrorCode="1190">The client private key properties are not provided while two-way SSL feature is enabled.</Error>

        <!-- X509 or Windows Truststore error thrown when ssl handshake failed.-->
        <Error Key="DSSslErrorMessage " Params="1" NativeErrorCode="1200">%1%</Error>
		
        <!-- Error thrown when Client certificate or Client key can not be read from the Client certificate or Client private key file. -->
        <Error Key="DSClientCertOrKeyFileLoadError" Params="0" NativeErrorCode="1210">Unable to load Client certificate or Client private key set via the connection attributes ClientCert or ClientPrivateKey. Please ensure the file exists, has read permission, and has the correct PEM format.</Error>

      <!--Rapidjson Error Messages-->
        <!-- Errors from rapidjson, rapidjson enum value is NativeErrorCode minus 2000. Messages from error.h in rapidjson library. -->
        <Error Key="DSkParseErrorNone" Params="0" NativeErrorCode="2000">JSON parsing error: No error.</Error>
        <Error Key="DSkParseErrorDocumentEmpty" Params="0" NativeErrorCode="2001">JSON parsing error: The document is empty.</Error>
        <Error Key="DSkParseErrorDocumentRootNotSingular" Params="0" NativeErrorCode="2002">JSON parsing error: The document root must not follow by other values.</Error>
        <Error Key="DSkParseErrorValueInvalid" Params="0" NativeErrorCode="2003">JSON parsing error: Invalid value.</Error>
        <Error Key="DSkParseErrorObjectMissName" Params="0" NativeErrorCode="2004">JSON parsing error: Missing a name for object member.</Error>
        <Error Key="DSkParseErrorObjectMissColon" Params="0" NativeErrorCode="2005">JSON parsing error: Missing a colon after a name of object member.</Error>
        <Error Key="DSkParseErrorObjectMissCommaOrCurlyBracket" Params="0" NativeErrorCode="2006">JSON parsing error: Missing a comma or '}' after an object member.</Error>
        <Error Key="DSkParseErrorArrayMissCommaOrSquareBracket" Params="0" NativeErrorCode="2007">JSON parsing error: Missing a comma or ']' after an array element.</Error>
        <Error Key="DSkParseErrorStringUnicodeEscapeInvalidHex" Params="0" NativeErrorCode="2008">JSON parsing error: Incorrect hex digit after \\u escape in string.</Error>
        <Error Key="DSkParseErrorStringUnicodeSurrogateInvalid" Params="0" NativeErrorCode="2009">JSON parsing error: The surrogate pair in string is invalid.</Error>
        <Error Key="DSkParseErrorStringEscapeInvalid" Params="0" NativeErrorCode="2010">JSON parsing error: Invalid escape character in string.</Error>
        <Error Key="DSkParseErrorStringMissQuotationMark" Params="0" NativeErrorCode="2011">JSON parsing error: Missing a closing quotation mark in string.</Error>
        <Error Key="DSkParseErrorStringInvalidEncoding" Params="0" NativeErrorCode="2012">JSON parsing error: Invalid encoding in string.</Error>
        <Error Key="DSkParseErrorNumberTooBig" Params="0" NativeErrorCode="2013">JSON parsing error: Number too big to be stored in double.</Error>
        <Error Key="DSkParseErrorNumberMissFraction" Params="0" NativeErrorCode="2014">JSON parsing error: Miss fraction part in number.</Error>
        <Error Key="DSkParseErrorNumberMissExponent" Params="0" NativeErrorCode="2015">JSON parsing error: Miss exponent in number.</Error>
        <Error Key="DSkParseErrorTermination" Params="0" NativeErrorCode="2016">JSON parsing error: Parsing was terminated.</Error>
        <Error Key="DSkParseErrorUnspecificSyntaxError" Params="0" NativeErrorCode="2017">JSON parsing error: Unspecific syntax error.</Error>

      <!-- Error thrown when the column doesn't exist. -->
      <Error Key="InvalidColumnNum" Params="1" NativeErrorCode="2018">%1% doesn't exist; BadColumnException.</Error>
      
      <!-- Error thrown when the user agent entry is invalid. -->
      <Error Key="InvalidUserAgentEntry" Params="0" NativeErrorCode="2019">Invalid user agent entry.</Error>
    
      <!-- Error thrown when the user agent comment is not enclosed in parentheses. -->
      <Error Key="UserAgentCommentNotEnclosedInParen" Params="0" NativeErrorCode="2020">Invalid user-agent string. The entire comment must be enclosed in parentheses.</Error>

      <!-- Error thrown when the user agent comment contains an invalid character. -->
      <Error Key="InvalidCharacterInUserAgentComment" Params="1" NativeErrorCode="2021">Invalid character '%1%' found in user-agent comment.</Error>

      <!-- Error thrown when the user agent product contains an invalid character. -->
      <Error Key="InvalidCharacterInUserAgentProductName" Params="1" NativeErrorCode="2022">Invalid character '%1%' found in user-agent product name.</Error>

      <!-- Error thrown when the user agent product version contains an invalid character. -->
      <Error Key="InvalidCharacterInUserAgentProductVer" Params="1" NativeErrorCode="2023">Invalid character '%1%' found in user-agent product version.</Error>

      <!-- Error thrown when an empty product name is specific in the user-agent entry. -->
      <Error Key="UserAgentEmptyProductName" Params="0" NativeErrorCode="2024">Empty product name is not allowed in the user-agent entry.</Error>

      <!-- Error thrown when an empty product version is specific in the user-agent entry. -->
      <Error Key="UserAgentEmptyProductVer" Params="0" NativeErrorCode="2025">Empty product version is not allowed in the user-agent entry.</Error>

      <!-- Error thrown when an invalid log level is specified. -->
      <Error Key="InvalidLogLevel" Params="1" NativeErrorCode="2026">Invalid log level '%1%' specified.</Error>

      <!-- Error generated when an instance of Simba::Support::Promise is destroyed before it it used to set it's corresponding Future's value/exception. -->
      <Error Key="DSFutureNotSetAtPromiseDestruction" Params="0" NativeErrorCode="50410">Future value/error not set before parent Promise object was destroyed.</Error>

      <!-- Error thrown when it's attempted to set a Future multiple times. -->
      <Error Key="DSFutureAlreadySet" NativeErrorCode="50411">Attempted to set Future value/error after it had already been set.</Error>

      <!-- Error thrown when Future::Get is called on an un-set future. -->
      <Error Key="DSFutureNotSet" NativeErrorCode="50412">Attempted to set Future value/error after it had already been set.</Error>

      <!-- Error thrown when an error occurred while decompressing LZ4 frames. -->
      <Error Key="DSLZ4FDecompressionError" Params="3" NativeErrorCode="60000">%1%An error occurred while attempting to decompress LZ4 frames. The LZ4 API function %2% returned an error. Error Detail: %3%</Error>

      <!-- Error thrown when the LZ4F_decompress function finished the decompression process but there is compressed data remaining that was not consumed. -->
      <Error Key="DSLZ4FCompressedDataMissedError" Params="2" NativeErrorCode="60001">%1%Decompression completed with %2% bytes of compressed data not consumed.</Error>

      <!-- Error thrown when the decompressed data size is smaller than expected. -->
      <Error Key="DSLZ4FDecompressedDataSmallerThanExpectedError" Params="3" NativeErrorCode="60002">%1%The decompressed data is smaller than expected. The actual decompressed data size is %2% bytes while we expect %3% bytes.</Error>

      <!-- Error thrown when 0 bytes of compressed data is passed in for decompression but a non-zero bytes of decompressed data is expected. -->
      <Error Key="DSLZ4FMissingCompressedDataError" Params="2" NativeErrorCode="60003">%1%Zero bytes of compressed data was passed in for decompression while %2% bytes of decompressed data is expected.</Error>

      <!-- Error thrown when 0 bytes of decompressed data is expected while a non-zero bytes of compressed data was passed in for decompression. -->
      <Error Key="DSLZ4FIncorrectExpectedDecompressedDataSizeError" Params="2" NativeErrorCode="60004">%1%Zero bytes of decompressed data is expected while %2% bytes of compressed data was passed in.</Error>
    </Package>
</Messages>
